# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BACla.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 665)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titulolabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titulolabel.setFont(font)
        self.titulolabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.titulolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titulolabel.setObjectName("titulolabel")
        self.horizontalLayout.addWidget(self.titulolabel)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_4.setStyleSheet("border:none")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.actualizarButton = QtWidgets.QPushButton(self.frame_4)
        self.actualizarButton.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.actualizarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actualizarButton.setStyleSheet("background-color: rgb(60, 130, 241);\n"
"border-radius:10px;\n"
"border: 1px solid #000000;")
        self.actualizarButton.setObjectName("actualizarButton")
        self.limpiarButton = QtWidgets.QPushButton(self.frame_4)
        self.limpiarButton.setGeometry(QtCore.QRect(100, 0, 71, 21))
        self.limpiarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.limpiarButton.setStyleSheet("background-color: rgb(60, 130, 241);\n"
"border-radius:10px;\n"
"border: 1px solid #000000;")
        self.limpiarButton.setObjectName("limpiarButton")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 200))
        self.scrollArea.setStyleSheet("/*Vertical scrollbar*/ \n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    width: 14px;\n"
"    border-radius: 7px;\n"
" }\n"
"/*Handle bar vertical*/\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(128, 128, 128);\n"
"    min_height:15px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"/*\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"Btn TOP-Scrollbar*/\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 858, 2500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setEnabled(True)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 2500))
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(13, 13, 321, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 550, 345, 19))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 1400, 691, 381))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.box2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.box2.setContentsMargins(0, 0, 0, 0)
        self.box2.setObjectName("box2")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(20, 1820, 371, 19))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.relevanciasTable = QtWidgets.QTableWidget(self.frame_3)
        self.relevanciasTable.setGeometry(QtCore.QRect(20, 1850, 691, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.relevanciasTable.sizePolicy().hasHeightForWidth())
        self.relevanciasTable.setSizePolicy(sizePolicy)
        self.relevanciasTable.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.relevanciasTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.relevanciasTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.relevanciasTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.relevanciasTable.setObjectName("relevanciasTable")
        self.relevanciasTable.setColumnCount(0)
        self.relevanciasTable.setRowCount(0)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(20, 2200, 187, 19))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 2233, 439, 18))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.eliminarVarBoton = QtWidgets.QPushButton(self.frame_3)
        self.eliminarVarBoton.setGeometry(QtCore.QRect(473, 2233, 200, 21))
        self.eliminarVarBoton.setMinimumSize(QtCore.QSize(200, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.eliminarVarBoton.setFont(font)
        self.eliminarVarBoton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eliminarVarBoton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(233, 233, 233);\n"
"border-radius:4px;\n"
"border: 1px solid #000000;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/x-mark-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminarVarBoton.setIcon(icon)
        self.eliminarVarBoton.setObjectName("eliminarVarBoton")
        self.datosFinalTable = QtWidgets.QTableWidget(self.frame_3)
        self.datosFinalTable.setGeometry(QtCore.QRect(20, 2270, 651, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datosFinalTable.sizePolicy().hasHeightForWidth())
        self.datosFinalTable.setSizePolicy(sizePolicy)
        self.datosFinalTable.setMinimumSize(QtCore.QSize(0, 100))
        self.datosFinalTable.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.datosFinalTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.datosFinalTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.datosFinalTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.datosFinalTable.setObjectName("datosFinalTable")
        self.datosFinalTable.setColumnCount(0)
        self.datosFinalTable.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 691, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.box.setContentsMargins(0, 0, 0, 0)
        self.box.setObjectName("box")
        self.covTable = QtWidgets.QTableWidget(self.frame_3)
        self.covTable.setGeometry(QtCore.QRect(20, 930, 691, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.covTable.sizePolicy().hasHeightForWidth())
        self.covTable.setSizePolicy(sizePolicy)
        self.covTable.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.covTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.covTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.covTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.covTable.setObjectName("covTable")
        self.covTable.setColumnCount(0)
        self.covTable.setRowCount(0)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 900, 288, 19))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(30, 1190, 446, 19))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(30, 1290, 261, 36))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.varAcButton = QtWidgets.QPushButton(self.frame_3)
        self.varAcButton.setGeometry(QtCore.QRect(420, 1300, 170, 21))
        self.varAcButton.setMinimumSize(QtCore.QSize(170, 21))
        self.varAcButton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varAcButton.setFont(font)
        self.varAcButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.varAcButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(233, 233, 233);\n"
"border-radius:4px;\n"
"border: 1px solid #000000;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/vision.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.varAcButton.setIcon(icon1)
        self.varAcButton.setIconSize(QtCore.QSize(20, 20))
        self.varAcButton.setObjectName("varAcButton")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(30, 1220, 171, 18))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.propVartextEdit = QtWidgets.QTextEdit(self.frame_3)
        self.propVartextEdit.setGeometry(QtCore.QRect(200, 1220, 521, 61))
        self.propVartextEdit.setObjectName("propVartextEdit")
        self.numCP = QtWidgets.QTextEdit(self.frame_3)
        self.numCP.setGeometry(QtCore.QRect(300, 1290, 111, 31))
        self.numCP.setObjectName("numCP")
        self.label_25 = QtWidgets.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(30, 1350, 241, 18))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_25.setObjectName("label_25")
        self.relevancia = QtWidgets.QTextEdit(self.frame_3)
        self.relevancia.setGeometry(QtCore.QRect(270, 1340, 111, 31))
        self.relevancia.setReadOnly(True)
        self.relevancia.setObjectName("relevancia")
        self.label_26 = QtWidgets.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(400, 1330, 261, 50))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_26.setObjectName("label_26")
        self.estandarTable = QtWidgets.QTableWidget(self.frame_3)
        self.estandarTable.setGeometry(QtCore.QRect(20, 580, 691, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estandarTable.sizePolicy().hasHeightForWidth())
        self.estandarTable.setSizePolicy(sizePolicy)
        self.estandarTable.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.estandarTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.estandarTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.estandarTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.estandarTable.setObjectName("estandarTable")
        self.estandarTable.setColumnCount(0)
        self.estandarTable.setRowCount(0)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulolabel.setText(_translate("Form", "Arboles de decisión (Pronóstico)"))
        self.actualizarButton.setText(_translate("Form", "Actualizar"))
        self.limpiarButton.setText(_translate("Form", "Limpiar"))
        self.label.setText(_translate("Form", "Mapa de Calor - Matriz de correlaciones"))
        self.label_2.setText(_translate("Form", "Estandarización de datos"))
        self.label_7.setText(_translate("Form", "Análisis de proporción de relevancias (cargas)"))
        self.label_10.setText(_translate("Form", "Eliminación de variables"))
        self.label_12.setText(_translate("Form", "Seleccione las variables que desee eliminar de la tabla de datos:"))
        self.eliminarVarBoton.setText(_translate("Form", "Elegir variables a eliminar"))
        self.label_5.setText(_translate("Form", "Matriz de Covarianzas"))
        self.label_22.setText(_translate("Form", "Definición del número de componentes principales"))
        self.label_23.setText(_translate("Form", "Con ayuda de la gráfica, ingrese el \n"
"número de componenetes principales:"))
        self.varAcButton.setText(_translate("Form", "Varianza Acumulada"))
        self.label_24.setText(_translate("Form", "Proporción de varianza:"))
        self.label_25.setText(_translate("Form", "Varianza Acumulada (Relevancia):"))
        self.label_26.setText(_translate("Form", "El porcentaje de relevancia \n"
"debe estar entre 75% y 90%"))
from . import resource_rc
