# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EDA3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 665)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titulolabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titulolabel.setFont(font)
        self.titulolabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.titulolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titulolabel.setObjectName("titulolabel")
        self.horizontalLayout.addWidget(self.titulolabel)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_4.setStyleSheet("border:none")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.actualizarButton = QtWidgets.QPushButton(self.frame_4)
        self.actualizarButton.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.actualizarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.actualizarButton.setStyleSheet("background-color: rgb(60, 130, 241);\n"
"border-radius:10px;\n"
"border: 1px solid #000000;")
        self.actualizarButton.setObjectName("actualizarButton")
        self.limpiarButton = QtWidgets.QPushButton(self.frame_4)
        self.limpiarButton.setGeometry(QtCore.QRect(100, 0, 71, 21))
        self.limpiarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.limpiarButton.setStyleSheet("background-color: rgb(60, 130, 241);\n"
"border-radius:10px;\n"
"border: 1px solid #000000;")
        self.limpiarButton.setObjectName("limpiarButton")
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 200))
        self.scrollArea.setStyleSheet("/*Vertical scrollbar*/ \n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    width: 14px;\n"
"    border-radius: 7px;\n"
" }\n"
"/*Handle bar vertical*/\n"
"QScrollBar::handle:vertical{\n"
"    background-color: rgb(128, 128, 128);\n"
"    min_height:15px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"/*\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"Btn TOP-Scrollbar*/\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -3227, 858, 3800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setEnabled(True)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 3800))
        self.frame_3.setStyleSheet("border:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(13, 13, 269, 19))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 550, 345, 19))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.describeTable = QtWidgets.QTableWidget(self.frame_3)
        self.describeTable.setGeometry(QtCore.QRect(10, 580, 741, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.describeTable.sizePolicy().hasHeightForWidth())
        self.describeTable.setSizePolicy(sizePolicy)
        self.describeTable.setMinimumSize(QtCore.QSize(0, 10))
        self.describeTable.setMaximumSize(QtCore.QSize(16777215, 500))
        self.describeTable.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.describeTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.describeTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.describeTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.describeTable.setObjectName("describeTable")
        self.describeTable.setColumnCount(0)
        self.describeTable.setRowCount(0)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 880, 741, 571))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.box2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.box2.setContentsMargins(0, 0, 0, 0)
        self.box2.setObjectName("box2")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(30, 1470, 288, 19))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 1500, 355, 19))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.describeTable2 = QtWidgets.QTableWidget(self.frame_3)
        self.describeTable2.setGeometry(QtCore.QRect(10, 1530, 741, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.describeTable2.sizePolicy().hasHeightForWidth())
        self.describeTable2.setSizePolicy(sizePolicy)
        self.describeTable2.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.describeTable2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.describeTable2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.describeTable2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.describeTable2.setObjectName("describeTable2")
        self.describeTable2.setColumnCount(0)
        self.describeTable2.setRowCount(0)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 1720, 311, 19))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 1760, 741, 751))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.box3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.box3.setContentsMargins(0, 0, 0, 0)
        self.box3.setObjectName("box3")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(20, 2520, 333, 19))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.describeTable3 = QtWidgets.QTableWidget(self.frame_3)
        self.describeTable3.setGeometry(QtCore.QRect(20, 2550, 731, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.describeTable3.sizePolicy().hasHeightForWidth())
        self.describeTable3.setSizePolicy(sizePolicy)
        self.describeTable3.setStyleSheet("QScrollBar:horizontal {\n"
"            border: none;\n"
"            background-color: rgb(255, 255, 255);\n"
"            height: 14px;\n"
"            margin: 0px 26px 0 26px;\n"
"          border-radius: 7px;\n"
"        }\n"
"\n"
"        QScrollBar::handle:horizontal {\n"
"           background-color: rgb(128, 128, 128);\n"
"            min-width: 15px;\n"
"          border-radius: 7px;\n"
"        }\n"
"QScrollBar::handle:horizontal:pressed{\n"
"\n"
"    background-color: rgb(78, 78, 78);\n"
"}\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"")
        self.describeTable3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.describeTable3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.describeTable3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.describeTable3.setObjectName("describeTable3")
        self.describeTable3.setColumnCount(0)
        self.describeTable3.setRowCount(0)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 3002, 771, 741))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.box4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.box4.setContentsMargins(0, 0, 0, 0)
        self.box4.setObjectName("box4")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 2952, 318, 19))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 39, 741, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.box = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.box.setContentsMargins(0, 0, 0, 0)
        self.box.setObjectName("box")
        self.layoutWidget = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 820, 657, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.varCajas = QtWidgets.QPushButton(self.layoutWidget)
        self.varCajas.setMinimumSize(QtCore.QSize(200, 21))
        self.varCajas.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.varCajas.setFont(font)
        self.varCajas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.varCajas.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(233, 233, 233);\n"
"border-radius:4px;\n"
"border: 1px solid #000000;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/search-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.varCajas.setIcon(icon)
        self.varCajas.setObjectName("varCajas")
        self.gridLayout_2.addWidget(self.varCajas, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titulolabel.setText(_translate("Form", "Análisis Exploratorio de Datos (EDA)"))
        self.actualizarButton.setText(_translate("Form", "Actualizar"))
        self.limpiarButton.setText(_translate("Form", "Limpiar"))
        self.label.setText(_translate("Form", "Histograma de Vriables Numéricas"))
        self.label_2.setText(_translate("Form", "Resumen estadístico de variables numéricas"))
        self.label_5.setText(_translate("Form", "Distribución de variables categóricas"))
        self.label_6.setText(_translate("Form", "Resumen estadístico de variables categóricas"))
        self.label_7.setText(_translate("Form", "Histogramas de Vriables Categóricas"))
        self.label_9.setText(_translate("Form", "Identificación de relaciones entre variables"))
        self.label_11.setText(_translate("Form", "Mapa de calor - matríz de correlaciones"))
        self.label_3.setText(_translate("Form", "Diagramas de caja para detectar posibles valores atípicos"))
        self.label_4.setText(_translate("Form", "Seleccione las variables que desee graficar en diagrama de caja:"))
        self.varCajas.setText(_translate("Form", "Elegir variables a graficar"))
from . import resource_rc
